### ISSUE TITLE
Won't compile on macOS 10.15

### ISSUE THREAD

**Issue by lukejames1111** [rehrumesh/atom-sass#19]
When I go to try and compile .scss files I get the following error:

`Errno::EROFS: Read-only file system @ dir_s_mkdir - ./.sass-cache`

There should be a way to disable the cache in the settings.

**Comment by theoryforcestudio** [comment]
any update?

**Comment by lukejames1111** [comment]
Nope, I ditched Atom altogether for VS Studio Code in the end
